// components/TestimonialsSection.jsx
import React from "react";
const TestimonialsSection = () => {
    return (
      <section id="testimonials" className="bg-white py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-4xl font-bold text-blue-700 mb-12">What Our Clients Say</h2>
  
          <div className="flex flex-col md:flex-row justify-center items-center gap-8">
            {/* Testimonial Card 1 */}
            <div className="border p-6 rounded-2xl shadow-lg hover:shadow-2xl transition-transform duration-300 ease-in-out max-w-sm">
              <p className="text-gray-600 mb-4">"AI Recruiter saved us hundreds of hours by automating first-round interviews. Highly recommend!"</p>
              <h4 className="font-bold text-gray-800">— Jane Smith, HR Manager</h4>
            </div>
  
            {/* Testimonial Card 2 */}
            <div className="border p-6 rounded-2xl shadow-lg hover:shadow-2xl transition-transform duration-300 ease-in-out max-w-sm">
              <p className="text-gray-600 mb-4">"The feedback reports generated by the AI were incredibly detailed and insightful."</p>
              <h4 className="font-bold text-gray-800">— Michael Brown, Talent Acquisition Lead</h4>
            </div>
  
            {/* Testimonial Card 3 */}
            <div className="border p-6 rounded-2xl shadow-lg hover:shadow-2xl transition-transform duration-300 ease-in-out max-w-sm">
              <p className="text-gray-600 mb-4">"A true game-changer for remote hiring! It streamlined everything from screening to feedback."</p>
              <h4 className="font-bold text-gray-800">— Lisa White, Hiring Consultant</h4>
            </div>
          </div>
        </div>
      </section>
    );
  };

  export default TestimonialsSection;
  